[
   {
      "id":"01",
      "fields":{
         "company":"ikea",
         "colors":[
            "#f15025",
            "#222"
         ],
         "featured":true,
         "price":2224,
         "title":"Gatorade Whey Protein Recover Bars, Peanut Butter Chocolate",
         "image":[
            {
               "id":"01",
               "url":"./img/products/01.jpg",
               "filename":"product-1.jpg",
               "size":62864,
               "type":"image/jpg",
               "thumbnails":{
                  "small":{
                     "url":"./img/products/01.jpg",
                     "width":56,
                     "height":36
                  },
                  "large1":{
                     "url":"./img/products/01.jpg",
                     "width":149,
                     "height":149
                  },
                  "large2":{
                     "url":"./img/products/overlay/01.jpg",
                     "width":149,
                     "height":149
                  }
               }
            }
         ]
      }
   },
   {
      "id":"02",
      "fields":{
         "company":"ikea",
         "colors":[
            "#f15025",
            "#222"
         ],
         "featured":true,
         "price":1390,
         "title":"Soft Croissant, Caramel Dulce De Leche Filling, Perfect Breakfast",
         "image":[
            {
               "id":"02",
               "url":"./img/products/02.jpg",
               "filename":"product-2.jpg",
               "size":62864,
               "type":"image/jpg",
               "thumbnails":{
                  "small":{
                     "url":"./img/products/02.jpg",
                     "width":56,
                     "height":36
                  },
                  "large1":{
                     "url":"./img/products/02.jpg",
                     "width":149,
                     "height":149
                  },
                  "large2":{
                     "url":"./img/products/overlay/02.jpg",
                     "width":149,
                     "height":149
                  }
               }
            }
         ]
      }
   },
   {
      "id":"03",
      "fields":{
         "company":"ikea",
         "colors":[
            "#f15025",
            "#222"
         ],
         "featured":true,
         "price":1299,
         "title":"Grandma's Cookies Variety Pack of 30",
         "image":[
            {
               "id":"03",
               "url":"./img/products/03.jpg",
               "filename":"product-3.jpg",
               "size":62864,
               "type":"image/jpg",
               "thumbnails":{
                  "small":{
                     "url":"./img/products/03.jpg",
                     "width":56,
                     "height":36
                  },
                  "large1":{
                     "url":"./img/products/03.jpg",
                     "width":149,
                     "height":149
                  },
                  "large2":{
                     "url":"./img/products/overlay/03.jpg",
                     "width":149,
                     "height":149
                  }
               }
            }
         ]
      }
   },
   {
      "id":"04",
      "fields":{
         "company":"ikea",
         "colors":[
            "#f15025",
            "#222"
         ],
         "featured":true,
         "price":1999,
         "title":"Milk-Bone Flavor Snacks Dog Treats for Dogs",
         "image":[
            {
               "id":"04",
               "url":"./img/products/04.jpg",
               "filename":"product-4.jpg",
               "size":62864,
               "type":"image/jpg",
               "thumbnails":{
                  "small":{
                     "url":"./img/products/04.jpg",
                     "width":56,
                     "height":36
                  },
                  "large1":{
                     "url":"./img/products/04.jpg",
                     "width":149,
                     "height":149
                  },
                  "large2":{
                     "url":"./img/products/overlay/04.jpg",
                     "width":149,
                     "height":149
                  }
               }
            }
         ]
      }
   },
   {
      "id":"05",
      "fields":{
         "company":"ikea",
         "colors":[
            "#f15025",
            "#222"
         ],
         "featured":true,
         "price":2000,
         "title":"Sambucus Sugar-Free Elderberry Syrup, Herbal Supplements",
         "image":[
            {
               "id":"05",
               "url":"./img/products/05.jpg",
               "filename":"product-5.jpg",
               "size":62864,
               "type":"image/jpg",
               "thumbnails":{
                  "small":{
                     "url":"./img/products/05.jpg",
                     "width":56,
                     "height":36
                  },
                  "large1":{
                     "url":"./img/products/05.jpg",
                     "width":149,
                     "height":149
                  },
                  "large2":{
                     "url":"./img/products/overlay/05.jpg",
                     "width":149,
                     "height":149
                  }
               }
            }
         ]
      }
   },
   {
      "id":"06",
      "fields":{
         "company":"ikea",
         "colors":[
            "#f15025",
            "#222"
         ],
         "featured":true,
         "price":1399,
         "title":"3 Pack Organic and Unsweetned Barbeque & Steak Sauce",
         "image":[
            {
               "id":"06",
               "url":"./img/products/06.jpg",
               "filename":"product-6.jpg",
               "size":62864,
               "type":"image/jpg",
               "thumbnails":{
                  "small":{
                     "url":"./img/products/06.jpg",
                     "width":56,
                     "height":36
                  },
                  "large1":{
                     "url":"./img/products/06.jpg",
                     "width":149,
                     "height":149
                  },
                  "large2":{
                     "url":"./img/products/overlay/06.jpg",
                     "width":149,
                     "height":149
                  }
               }
            }
         ]
      }
   },
]